### ISSUE TITLE
 After update everything defective!

### ISSUE THREAD

**Issue by Ghost4255** [ajenti/ajenti#1008]
Hello,

You have renewed one or more data a few hours ago and I have installed the update via my ssh section "apt-get update / upgrade".
Now Ajenti is broken it is no longer accessible.
What's wrong with the update has me all shot!

LG

**Comment by Ghost4255** [comment]
update-rc.d: error: unable to read /etc/init.d/ajenti
/var/lib/dpkg/info/ajenti.postinst: 4: /var/lib/dpkg/info/ajenti.postinst: ajenti-ssl-gen: not found

**Comment by dinho-afsn** [comment]
All my servers down after update!!!! please howto solve???

Someone help me please, my sites fell after this update and it does not work
Update-rc.d: error: unable to read /etc/init.d/ajenti
/var/lib/dpkg/info/ajenti.postinst: 4: /var/lib/dpkg/info/ajenti.postinst: ajenti-ssl-gen: not found

**Comment by Eugeny** [comment]
I've updated the package, please `apt-get update` and `apt-get install ajenti` again.

**Comment by mikestp27** [comment]
Still have the problem even after update 1.2.23.9 (running on Ubuntu 14.04).  
I followed instructions above and ran `apt-get update` and `apt-get install ajenti`  and I got the following error:
`Preparing to unpack .../ajenti_1.2.23.9_all.deb ...`
`Unpacking ajenti (1.2.23.9) ...`
`Setting up ajenti (1.2.23.9) ...`
`/var/lib/dpkg/info/ajenti.postinst: line 4: ajenti-ssl-gen: command not found`
`Now start Ajenti with 'service ajenti restart'`

When I try to (re)start ajenti, I get the following message:
`/etc/init.d/ajenti: line 52: /usr/bin/ajenti-panel: No such file or directory`

**Comment by SantaGitHub** [comment]
@mikestp27 me too

**Comment by Eugeny** [comment]
Could you please try again with `1.2.23.10`?

**Comment by marcolussetti** [comment]
1.2.23.10 fixes everything for me! Thank you so much @Eugeny for the quick fix!

**Comment by timlaughlin** [comment]
@Eugeny It looks like there isn't a 1.2.23.10 for debian but 1.2.23.9 is the correct size..

ajenti_1.2.23.9_all.deb                            13-Jan-2017 17:08             1720858

**Comment by mikestp27** [comment]
My servers are running again with `1.2.23.10`; I'm running Ubuntu 14.04.   Thank you.
