### ISSUE TITLE
Ajenti not working in Debian Jessie

### ISSUE THREAD

**Issue by hydrosIII** [ajenti/ajenti#702]
Problem with gevent support...

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766867

I installed gevent with easy install, following the instructions to solve the similar  ubuntu issue: https://github.com/Eugeny/ajenti/issues/618

Did not work. Now ajenti is not starting:

```
08.04.2015 08:51 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
08.04.2015 08:51 ajenti-panel:130              INFO  Ajenti starting in foreground
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 137, in <module>
    from ajenti import core
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 18, in <module>
    import ajenti.licensing
  File "/usr/lib/pymodules/python2.7/ajenti/licensing.py", line 8, in <module>
    from ajenti.ipc import IPCHandler
  File "/usr/lib/pymodules/python2.7/ajenti/ipc.py", line 2, in <module>
    from gevent.pywsgi import WSGIServer, WSGIHandler
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 12, in <module>
    from gevent import socket
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
```

**Comment by Xefir** [comment]
Please refer to this bug in gevent repo https://github.com/gevent/gevent/issues/513

And the fix you have to apply https://github.com/gevent/gevent/pull/517/files

**Comment by hydrosIII** [comment]
Hi, this is solved with your patch. Thank you.
it worked for a few days, but then it failed in the browser with the message, that no common protocol was found. For now Ajent is out from my Debian Jessie, I will wait for the official release of Ajenti in Jessie to install it again. Do you want me to open other issue of the new problem and investigate a lillte further? thanks.

**Comment by fffizzz** [comment]
Same issue here, slightly different error. Occurred after upgrade to Debian 8 Stable though..

**Comment by K-Ko** [comment]
+1

**Comment by pfz** [comment]
+1. 
@hydrosIII The patch actually works. Here what I did, replacing gevent from debian/jessie by gevent from easy_install (like you did), and doing this;

``` bash
aptitude install python-setuptools python-dev
easy_install -U gevent
sed -i -e s/ssl_version=PROTOCOL_SSLv3/ssl_version=PROTOCOL_SSLv23/ /usr/local/lib/python2.7/dist-packages/gevent-1.
0.1-py2.7-linux-x86_64.egg/gevent/ssl.py
service ajenti restart
```

It works fine.

Here the original ajenti.log before that : 

```
2015-05-03 22:47:19,186 INFO     core.run(): Ajenti 1.2.22.19 running on platform: debian
2015-05-03 22:47:19,186 INFO    : Ajenti 1.2.22.19 running on platform: debian
 manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-05-03 22:47:19,194 INFO    : Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-05-03 22:47:19,236 INFO    : Disabling systemd service manager: global name 'SystemdService' is not defined
2015-05-03 22:47:19,241 WARNING :  *** [elements] Plugin error: format error
2015-05-03 22:47:19,633 INFO    : Starting server on (u'0.0.0.0', 8000)
2015-05-03 22:47:19,635 INFO    : SSL enabled: /etc/ajenti/ajenti.pem
2015-05-03 22:47:19,640 INFO    : Starting new HTTP connection (1): meta.ajenti.org
", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f197ffd92d0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7f1980002c50 fileno=8 address=0.0.0.0:8000>>(<socket at 0x7f19807b2d10 fileno=13 sock=127.0.0.1, ('127.0.0.1', 39861))> failed with NameError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f197ffd92d0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7f1980002c50 fileno=8 address=0.0.0.0:8000>>(<socket at 0x7f19807b2d10 fileno=13 sock=127.0.0.1, ('127.0.0.1', 39862))> failed with NameError
```

**Comment by K-Ko** [comment]
Forgot to say, did the same as @pfz before and works too.

**Comment by tylerhoot** [comment]
... having the same sorta issue ssl issue

**Comment by tylerhoot** [comment]
cant get the above fix to work

**Comment by pfz** [comment]
@tylerhoot at which step are you stuck ?

**Comment by stopspazzing** [comment]
I had same issue, I fixed it myself with a simple edit. The problem is due to the fact that gevent hasn't updated to 1.03 and applied the fixes that are ready to go. Not sure what their hold up is but whatever.

@tylerhoot
How to fix:
vi /usr/lib/python2.7/dist-packages/gevent/ssl.py
-->Find "ssl_version=PROTOCOL_SSLv3" - Change to "ssl_version=PROTOCOL_SSLv23"
service ajenti restart

Takes a simple 20 seconds. On next gevent update will be this way anyways.

**Comment by Mel0ne** [comment]
@stopspazzing i have the same problem, but in ssl.py a have already PROTOCOL_SSLv23

**Comment by stopspazzing** [comment]
@Mel0ne Did you restart the process? Should work after a restart. You sure you are getting same error? because if it's same issue then would be same error.

**Comment by Mel0ne** [comment]
@stopspazzing method by @pfz  helped me :)

**Comment by brad999** [comment]
After following the instructions from @pfz I am able to get to the login page, log in, and get nothing but a blank page with the ajenti header.

This is what is in my ajenti.log. Any advice?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 103, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 184, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 294, in handle_one_request
    self.requestline = self.read_requestline()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 287, in read_requestline
    return self.rfile.readline(MAX_REQUEST_LINE)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 415, in recv
    return socket.recv(self, buflen, flags)
TypeError: 'member_descriptor' object is not callable
<Greenlet at 0x7fc634487870: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fc635b7e990 fileno=8 address=0.0.0.0:8000>>(<socket at 0x7fc634079910 fileno=-1>, ('192.168.1.155', 12549))> failed with TypeError
```

**Comment by pfz** [comment]
@brad999 I'm no py expert, but it looks like a socket binding error. May be you still have an ajenti process. Try `netstat -apnt |grep LISTEN|grep ":8000"` to find anything attached to *:8000

**Comment by brad999** [comment]
@pfz Below are the results of the netstat. It shows that ajenti is running on 8000.

```
root@host:~# netstat -apnt | grep LISTEN | grep ":8000"
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      5194/python
```

```
root      5194     1  0 May24 ?        00:00:02 /usr/bin/python /usr/bin/ajenti-panel -d
```

**Comment by pfz** [comment]
Hi, sorry i didn't see that, but my patch is supposed to modify a file name ....gevent-1.0.1... but yours is 1.0.2. Juste updated my code : 

```
aptitude install python-setuptools python-dev
easy_install -U gevent
sed -i -e s/ssl_version=PROTOCOL_SSLv3/ssl_version=PROTOCOL_SSLv23/ /usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/ssl.py
service ajenti restart
```

**Comment by bbbenji** [comment]
I am experiencing the same issue. I did not apply the fix because my ```/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/ssl.py``` already contains ```ssl_version=PROTOCOL_SSLv23```. After logging into Ajenti with SSL enabled all I get is the header bar and a blank page.

Error:
```SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
<Greenlet at 0x7f668a699e10: _close_when_done(<socket at 0x7f6689ad9fd0 fileno=[Errno 9] Bad fil, ('xx.xxx.xx.xx', 43137))> failed with SSLError```

Any ideas?

**Comment by Xefir** [comment]
The latest version you'll get with `sudo easy_install -U gevent` 's command, witch is 1.1b3, works fine with the current version of ajenti.

Can you try it and come back here if you the problems still occurs ?

**Comment by flavio-pessoa** [comment]
To fix problem, execute the commands below.

1) Install python tools and dev
$ install python-setuptools python-dev

2) Install gevent, in version 1.1b3
$ easy_install -U gevent==1.1b3

3) Downgrade ssl version of protocol
$ sed -i -e s/ssl_version=PROTOCOL_SSLv3/ssl_version=PROTOCOL_SSLv23/ /usr/local/lib/python2.7/dist-packages/gevent-1.1b3-py2.7-linux-x86_64.egg/gevent/ssl.py

4) Restart ajenti 
$ service ajenti restart

**Comment by Xefir** [comment]
The 3rd step seems to be useless on 1.1b3 (i don't have to do it and it works without)

**Comment by StefanoFrazzetto** [comment]
[DEBIAN 8] -ERR_CONNECTION_RESET on Chrome

I tried every solution but nothing works. 
I also tried to edit the ssl version to sslv23 in /usr/lib/python3.4/dist-packages/ssl.py but it didn't work.
Ajenti only works without SSL for me...

**Comment by steschi** [comment]
Im also not able to use ajenti with SSL.
Debian 8.2
python 2.7.9

Result of: pip show gevent

```
---
Name: gevent
Version: 1.1b5
Location: /usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg
Requires: greenlet
```

Result of: pip freeze

```
Mako==1.0.0
MarkupSafe==0.23
Pillow==2.6.1
Pygments==2.0.1
SOAPpy==0.12.22
ajenti==1.2.22.24
argparse==1.2.1
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
defusedxml==0.4.1
docutils==0.12
gevent==1.1b5
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.9
html5lib==0.999
lockfile==0.8
lxml==3.4.0
ndg-httpsclient==0.3.2
numpy==1.8.2
passlib==1.6.1
ply==3.4
psutil==2.1.1
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
pygobject==3.14.0
python-apt==0.9.3.12
python-catcher==0.1.7
python-daemon==1.5.5
python-debian==0.1.27
python-debianbts==1.11
python-exconsole==0.1.5
python-ldap==2.4.10
reconfigure==0.1.72
reportbug==6.6.3
requests==2.4.3
roman==2.0.0
six==1.8.0
urllib3==1.9.1
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3
```

**Comment by flavio-pessoa** [comment]
I had done as the user stopspazzing, mentioned , and it was the same problem as the user Schinti95.
I was with the version of gevent on version 1.1b5, when I forced the installation in version 1.1b3, the problem disappeared, tested with Ubuntu in version 14.10

**Comment by erm3nda** [comment]
@flavio-pessoa Thank you, downgrading SSL worked.

**Comment by joereynolds** [comment]
@flavio-pessoa Thanks! I followed steps 1, 2, and 4 and it works now

**Comment by john-clark** [comment]
# easy_install -U gevent==1.1b3
Searching for gevent==1.1b3
Reading https://pypi.python.org/simple/gevent/
Best match: gevent 1.1b3
Downloading https://pypi.python.org/packages/86/a8/560eda4b396e2381943a606bb871bda8aaf03f636e839b91e712893ce468/gevent-1.1b3.tar.gz#md5=ebc328363bc814af51547dd25d817e3c
Processing gevent-1.1b3.tar.gz
Writing /tmp/easy_install-8D333i/gevent-1.1b3/setup.cfg
Running gevent-1.1b3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8D333i/gevent-1.1b3/egg-dist-tmp-BCPflo
Running '(cd  "/tmp/easy_install-8D333i/gevent-1.1b3/libev"  && /bin/sh ./configure   && mv config.h "$OLDPWD") > configure-output.txt' in /tmp/easy_install-8D333i/gevent-1.1b3/build/temp.linux-x86_64-2.7/libev
./configure: line 2684: printf: write error: Broken pipe
configure: error: in `/tmp/easy_install-8D333i/gevent-1.1b3/libev':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==5.5.1', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2199, in main
    lambda: setup(
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2185, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2202, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 408, in <module>
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 396, in run_setup
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 22, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 259, in build_extension
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 256, in gevent_prepare
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 162, in configure_libev
  File "/tmp/easy_install-8D333i/gevent-1.1b3/setup.py", line 138, in _system
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/easy_install-8D333i/gevent-1.1b3/libev"  && /bin/sh ./configure   && mv config.h "$OLDPWD") > configure-output.txt' returned non-zero exit status 1

**Comment by erm3nda** [comment]
2016-05-11 21:22 GMT+02:00 John Clark notifications@github.com:

> configure: error: no acceptable C compiler found in $PATH

configure: error: no acceptable C compiler found in $PATH

> Because no acceptable C compiler was found, the final line

cd "/tmp/easy_install-8D333i/gevent-1.1b3/libev" && /bin/sh ./configure &&

> mv config.h "$OLDPWD") > configure-output.txt'

will not work. Try yourself to run

cd /tmp/easy_install-8D333i/gevent-1.1b3/libev && ./configure


Doublecheck for easy_install-xxxxxxx name folder according to your actual
execution. If the old /tmp is still here you can try it.
This way you'll see more info.

I would suggest you to install the devel libraries, such as

sudo apt-get install gcc


or even better, the essential pack

sudo apt-get install build-essentials


Some (most of good ones or big ones) does build some libraries while
installing them, like scipy and much others.

~~ Self signed ~~

**Comment by john-clark** [comment]
works now

```
apt-get install built-essential python-setuptools python-dev
easy_install -U gevent
service ajenti restart
```

**Comment by ghost** [comment]
Hi,
@john-clark with `apt-get install build-essential python-setuptools python-dev` it's work better

**Comment by mitchellurgero** [comment]
Most of the options above do not work as of today Don't know why.
On Debian 8(Jessie) I had to do this comment's answer to the problem:

https://github.com/ajenti/ajenti/issues/702#issuecomment-141835291

**Comment by oblx** [comment]
Same as above, debian 8 and [#702 (comment)](https://github.com/ajenti/ajenti/issues/702#issuecomment-141835291) fixed the problem.

**Comment by avmarchenko** [comment]
Also for me, debian 8 and https://github.com/ajenti/ajenti/issues/702#issuecomment-218565730 fixed the problem.

**Comment by ghost** [comment]
Is this going to be fixed? Ajenti doesn't work with SSL with Debian 8. You need to manuall install gevent 1.1b3.

**Comment by Eugeny** [comment]
This has already been fixed in #903 (update `python-gevent` and `python-gevent-socketio` to the latest versions)

**Comment by 5nafu** [comment]
Unfortunatly the package referenced in #903 does not fix the issue for debian jessie.

```
# dpkg -l |grep "gevent\|ajenti"
ii  ajenti                          1.2.23.8                    all          Server administration web interface
ii  python-gevent                   1.0.1-2                     amd64        gevent is a coroutine-based Python networking library
ii  python-gevent-socketio          0.3.7.99-1                  all          SocketIO server based on the Gevent pywsgi server, a Python
ii  python-gevent-websocket         0.9.3-1                     all          websocket library for the gevent networking library
```

The python-gevent has a higher version in the upstream repositories than in the ajenti one:

```
# apt-cache madison python-gevent
python-gevent |    1.0.1-2 | http://mirror.hetzner.de/debian/packages/ jessie/main amd64 Packages
python-gevent |    1.0.1-2 | http://http.debian.net/debian/ jessie/main amd64 Packages
python-gevent | 0.13.6-1~bpo60+1 | http://repo.ajenti.org/debian/ main/main amd64 Packages
```

And trying to install the 0.13 Version manually results in errors due to unmet dependencies:

```
# apt-get install python-gevent=0.13.6-1~bpo60+1
[...]
The following packages have unmet dependencies:
 python-gevent : Depends: libevent-1.4-2 (>= 1.4.13-stable) but it is not installable
                 Depends: python (< 2.7) but 2.7.9-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by 5nafu** [comment]
I can however confirm that using the [jessie backports ](https://backports.debian.org/Instructions/) and installing the `python-gevent` package before the `python-gevent-socketio_0.3.7.99-1_all.deb` referenced in [#903](https://github.com/ajenti/ajenti/issues/903#issuecomment-239786079) and `ajenti` works.

```
# apt-get -t jessie-backports install python-gevent
[...]
# wget -c http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
[...]
# dpkg -i python-gevent-socketio_0.3.7.99-1_all.deb
[...]
# apt-get install ajenti
[...]
```

The installed packages are now:

```
# dpkg -l |grep "gevent\|ajenti"
ii  ajenti                         1.2.23.8                    all          Server administration web interface
ii  python-gevent                  1.1.1-2~bpo8+1              amd64        gevent is a coroutine-based Python networking library
ii  python-gevent-socketio         0.3.7.99-1                  all          SocketIO server based on the Gevent pywsgi server, a Python
ii  python-gevent-websocket        0.9.3-1                     all          websocket library for the gevent networking library
```

Without the updated `python-gevent-socketio` I got an Unicode Error from `pywsgi.py` stating that my header (Access-Control-Max-Age) was not a string.

**Comment by Eugeny** [comment]
@5nafu thank you for the investigation. On the newer systems, there's no need to use our python-gevent package. I've also added the jessie-backports version to the repo just to be safe.
