### ISSUE TITLE
 Server error occured. This is likely a bug.

### ISSUE THREAD

**Issue by paulvilla** [ajenti/ajenti#871]
I have this message:

Request
GET /api/plugins/core/check-upgrade

Type
AttributeError

Message
'exceptions.TypeError' object has no attribute 'replace'

Traceback
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/ajenti_plugin_plugins/views.py", line 108, in handle_api_core_check_upgrade
    raise EndpointError(e)
  File "/usr/lib/python2.7/site-packages/aj/api/endpoint.py", line 22, in **init**
    self.message = message or six.u(inner)
  File "/usr/lib/python2.7/site-packages/six.py", line 647, in u
    return unicode(s.replace(r'\', r'\\'), "unicode_escape")
AttributeError: 'exceptions.TypeError' object has no attribute 'replace'

CentOS 7

**Comment by Xefir** [comment]
Fixed by https://github.com/Eugeny/reconfigure/pull/17. Can you update python-reconfigure, test and close if it's good ? :)

**Comment by snvad** [comment]
I have the same error on centos7. 

> Can you update python-reconfigure

Write more what to do, please. 

I have Python 2.7.5, `pip install -U reconfigure` -> reconfigure-0.1.79.
Error persists.
